In [1]:
pip install sentence-transformers scikit-learn

In [2]:
from sentence_transformers import SentenceTransformer, util
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

print("✅ Libraries Imported Successfully!\n")


✅ Libraries Imported Successfully!



In [3]:
model = SentenceTransformer('all-MiniLM-L6-v2')

print("✅ Pretrained Sentence-BERT Model Loaded!\n")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

C:\Users\suryansh\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\suryansh\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

✅ Pretrained Sentence-BERT Model Loaded!



In [4]:
sentences = [
    "I love playing football with my friends.",
    "Soccer is my favorite sport.",
    "The sun is shining bright today.",
    "Artificial Intelligence is transforming the world.",
    "I enjoy watching movies on weekends."
]

print("✅ Sentences Loaded:")
for s in sentences:
    print("-", s)
print("\n")

✅ Sentences Loaded:
- I love playing football with my friends.
- Soccer is my favorite sport.
- The sun is shining bright today.
- Artificial Intelligence is transforming the world.
- I enjoy watching movies on weekends.




In [5]:
embeddings = model.encode(sentences)

print("✅ Sentence Embeddings Generated! Shape:", embeddings.shape, "\n")

✅ Sentence Embeddings Generated! Shape: (5, 384) 



In [6]:
cosine_sim = cosine_similarity(embeddings)

print("📊 Cosine Similarity Matrix:")
print(np.round(cosine_sim, 3), "\n")

📊 Cosine Similarity Matrix:
[[1.    0.618 0.012 0.1   0.333]
 [0.618 1.    0.096 0.233 0.327]
 [0.012 0.096 1.    0.209 0.149]
 [0.1   0.233 0.209 1.    0.116]
 [0.333 0.327 0.149 0.116 1.   ]] 



In [7]:
query = "I like to play soccer."
query_embedding = model.encode([query])

similarities = cosine_similarity(query_embedding, embeddings)[0]
most_similar_idx = np.argmax(similarities)

print(f"🔍 Query: {query}")
print(f"Most Similar Sentence: {sentences[most_similar_idx]}")
print(f"Similarity Score: {similarities[most_similar_idx]:.3f}\n")

🔍 Query: I like to play soccer.
Most Similar Sentence: Soccer is my favorite sport.
Similarity Score: 0.754



In [8]:
corpus = [
    "The sky is clear and blue.",
    "I am going to play football after lunch.",
    "Artificial Intelligence and Machine Learning are related fields.",
    "It might rain today, take an umbrella!",
    "He scored a goal in the last match."
]

queries = [
    "What is AI?",
    "Who won the football match?",
    "Will it rain today?"
]

# Encode corpus and queries
corpus_embeddings = model.encode(corpus, convert_to_tensor=True)
query_embeddings = model.encode(queries, convert_to_tensor=True)

print("✅ Corpus and Queries Encoded!\n")

# Perform semantic search
for i, query in enumerate(queries):
    scores = util.cos_sim(query_embeddings[i], corpus_embeddings)[0]
    best_match = np.argmax(scores)
    print(f"🔹 Query: {query}")
    print(f"Best Match: {corpus[best_match]}")
    print(f"Similarity Score: {scores[best_match]:.3f}\n")

✅ Corpus and Queries Encoded!

🔹 Query: What is AI?
Best Match: Artificial Intelligence and Machine Learning are related fields.
Similarity Score: 0.588

🔹 Query: Who won the football match?
Best Match: He scored a goal in the last match.
Similarity Score: 0.421

🔹 Query: Will it rain today?
Best Match: It might rain today, take an umbrella!
Similarity Score: 0.741

